ALTER TABLE superstores_data 
	ALTER COLUMN customer_name TYPE VARCHAR(200),
	ALTER COLUMN ship_mode TYPE VARCHAR(200),
	ALTER COLUMN customer_id TYPE VARCHAR(200),
	ALTER COLUMN segment TYPE VARCHAR(200),
	ALTER COLUMN city TYPE VARCHAR(200),
	ALTER COLUMN state TYPE VARCHAR(200),
	ALTER COLUMN region TYPE VARCHAR(200),
	ALTER COLUMN product_id TYPE VARCHAR(200),
	ALTER COLUMN category TYPE VARCHAR(200),
	ALTER COLUMN sub_category TYPE VARCHAR(200),
	ALTER COLUMN product_name TYPE VARCHAR(200)
	
	;
